name: Publish
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: mkdir public
      - name: Build HTML
        uses: addnab/docker-run-action@v3
        with:
          image: there4/markdown-resume:2.3.1
          options: -v ${{ github.workspace }}:/resume:z
          run: md2resume html --template readable resume.md ./public
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public